### PR TITLE
Upstream DNS is now editable

### PR DESCRIPTION
**Pull request by b-reich**
Make the Upstream DNS easy editable
https://github.com/steamcache/generic/pull/53

### CODE REVIEW

**Review by ismaelzmirli — APPROVED** [review]

**Comment by TheKigen** [comment]
Please merge this.  I don't like using Google DNS due to their privacy policy and originally banned their IP from my network.  The other SteamCache containers accept UPSTREAM_DNS.

**Comment by b-reich** [comment]
@mintopia can you merge this requests?

**Comment by b-reich** [comment]
@TheKigen @malteserr checkout my repo please. I will maintaine a fork of the whole project.

**Comment by mintopia** [comment]
Sorry, I've been crazily busy. This has now been merged! Thank you very much for adding this.

**Pull request merged**
